### ISSUE TITLE
Create Hypha product website

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha-site#1]
# Objective
Create a website for the Hypha product.

## Who is the audience of this website?
This website is targeted at:
- funding organisations (organisations who may want to use Hypha for fund applications)
- technical implementers (developers, designers, etc who would be working on implementation of Hypha in an organisation)
- fund applicants
- possible open source contributors? (developers, UX designers, others who want to contribute to Hypha?)
- others?

## What does this website need to communicate?
- [ ] what hypha is (what it is not?)
- [ ] what Hypha can help users with
- [ ] what the "application processes" it supports (1 stage, 2 stage application process, internal/external reviewer, etc)
- [ ] examples of user journeys/use cases
  - [ ] @frjo suggested some video screen casts showing Hypha workflow: e.g. creating a fund/application, applying thru a form, reviewing applications
- [ ] who currently uses Hypha
- [ ] data ownership
- [ ] open source
- [ ] how to support Hypha
- [ ] about the Hypha team
- something else?

## Design / technical considerations
- localisation?
- [ ] provide some web analytics
- [ ] privacy preserving
- [ ] responsive
- [ ] unless there are objections we'll use @frjo's [Hugo Zen theme](https://themes.gohugo.io/theme/hugo-theme-zen/)

## Web address
[Hypha.app](https://Hypha.app)

## Tasks to be done at a later stage
- [ ] change GH repo addresses in website to the new github.com/HyphaApp/ addresses once everything is moved over

**Comment by ei8fdb** [comment]
@danblah, @saoun, @frjo, @fourthletter - if you have any things that "must be in here", please comment here.

@bumbleblue if you've done some sketches/possible designs on this, please add here! 👍

**Comment by frjo** [comment]
I have added the information from the Hypha README to the home page now, that’s a good start I think.

**Comment by ei8fdb** [comment]
@frjo Ah I was just doing that now! I'll pull your update now.
